import pathlib
from typing import Union, Tuple
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """

    def __init__(self, data_fname: Union[pathlib.Path, str]):
        if not isinstance(data_fname, (pathlib.Path, str)):
            raise TypeError("not path or string")
        self.data_fname = pathlib.Path(data_fname) if isinstance(data_fname, str) else data_fname
        if not self.data_fname.exists() or not self.data_fname.is_file():
            raise ValueError(f"does not exist")

    def read_data(self):
        """Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        df = pd.read_json(self.data_fname)
        if 'age' in df.columns:
            df['age'] = pd.to_numeric(df['age'], errors='coerce')
        questions = [col for col in df.columns if col.startswith('q')]
        for q in questions:
            df[q] = pd.to_numeric(df[q], errors='coerce')
        self.data = df

    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        """Calculates and plots the age distribution of the participants.

        Returns
        -------
        hist : np.ndarray
            Number of people in a given bin
        bins : np.ndarray
            Bin edges
        """
        ages = self.data['age'].dropna()
        bins = np.arange(0, 101, 10)
        hist, edges = np.histogram(ages, bins=bins)
        plt.figure()
        plt.hist(ages, bins=bins)
        plt.xlabel('Age')
        plt.ylabel('Count')
        plt.title('Age Distribution')
        return hist, edges

    def remove_rows_without_mail(self) -> pd.DataFrame:
        """Checks self.data for rows with invalid emails, and removes them.

        Returns
        -------
        df : pd.DataFrame
        A corrected DataFrame, i.e. the same table but with the erroneous rows removed and
        the (ordinal) index after a reset.
        """
        df = self.data.copy()
        def valid(email: str) -> bool:
            if not isinstance(email, str):
                return False
            if email.count('@') != 1:
                return False
            if email.startswith('@') or email.endswith('@'):
                return False
            if email.startswith('.') or email.endswith('.'):
                return False
            if '.' not in email:
                return False
            at = email.index('@')
            if at + 1 < len(email) and email[at+1] == '.':
                return False
            return True
        mask = df['email'].apply(valid)
        return df.loc[mask].reset_index(drop=True)

    def fill_na_with_mean(self) -> Tuple[pd.DataFrame, np.ndarray]:
        """Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student.

        Returns
        -------
        df : pd.DataFrame
            The corrected DataFrame after insertion of the mean grade
        arr : np.ndarray
                Row indices of the students that their new grades were generated
        """
        df = self.data.copy()
        questions = [col for col in df.columns if col.startswith('q')]
        rows = []
        for idx, row in df.iterrows():
            vals = row[questions]
            if vals.isna().any():
                mean_val = vals.mean(skipna=True)
                df.loc[idx, questions] = vals.fillna(mean_val)
                rows.append(idx)
        return df, np.array(rows)

    def score_subjects(self, maximal_nans_per_sub: int = 1) -> pd.DataFrame:
        """Calculates the average score of a subject and adds a new "score" column
        with it.

        If the subject has more than "maximal_nans_per_sub" NaN in his grades, the
        score should be NA. Otherwise, the score is simply the mean of the other grades.
        The datatype of score is UInt8, and the floating point raw numbers should be
        rounded down.

        Parameters
        ----------
        maximal_nans_per_sub : int, optional
            Number of allowed NaNs per subject before giving a NA score.

        Returns
        -------
        pd.DataFrame
            A new DF with a new column - "score".
        """
        df = self.data.copy()
        questions = [col for col in df.columns if col.startswith('q')]
        scores = []
        for _, row in df.iterrows():
            vals = row[questions]
            n_nans = vals.isna().sum()
            if n_nans > maximal_nans_per_sub:
                scores.append(pd.NA)
            else:
                mean_val = vals.mean(skipna=True)
                scores.append(int(np.floor(mean_val)))
        df['score'] = pd.Series(scores, dtype='UInt8')
        return df

    def correlate_gender_age(self) -> pd.DataFrame:
        """Looks for a correlation between the gender of the subject, their age
        and the score for all five questions.

        Returns
        -------
        pd.DataFrame
            A DataFrame with a MultiIndex containing the gender and whether the subject is above
            40 years of age, and the average score in each of the five questions.
        """
        df = self.data.copy().dropna(subset=['age'])
        questions = [col for col in df.columns if col.startswith('q')]
        age_flag = df['age'] > 40
        grouped = df.groupby([df['gender'], age_flag])[questions].mean()
        return grouped
