import pathlib, numpy as np, pandas as pd, matplotlib.pyplot as plt
from typing import Union, Tuple


class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """

    def __init__(self, data_fname: Union[pathlib.Path, str]):
        self.data_fname=pathlib.Path(data_fname)
        if not self.data_fname.exists():
            raise ValueError()
        self.data=None

    def read_data(self):
        """Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        self.data=pd.read_json(self.data_fname)
    
    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        """Calculates and plots the age distribution of the participants.

    Returns
    -------
    hist : np.ndarray
        Number of people in a given bin
    bins : np.ndarray
        Bin edges
        """
        ages=pd.to_numeric(self.data["age"], errors="coerce")
        hist, bins,_= plt.hist(ages,bins=np.arange(0, 101, 10))
        plt.xlabel("Age")
        plt.ylabel("Number of People")
        return hist,bins
    
    def remove_rows_without_mail(self) -> pd.DataFrame:
        """Checks self.data for rows with invalid emails, and removes them.

    Returns
    -------
    df : pd.DataFrame
    A corrected DataFrame, i.e. the same table but with the erroneous rows removed and
    the (ordinal) index after a reset.
        """
        invalid_emails = []
        for idx, email in self.data["email"].items():
            if (
                email[0] in {'.', '@'} or
                email[-1] in {'.', '@'} or
                email.count('@') != 1 or
                '.' not in email or
                email.split('@')[1][0] == '.'
            ):
                invalid_emails.append(idx)
        self.data = self.data.drop(index=invalid_emails).reset_index(drop=True)
        return self.data

    def fill_na_with_mean(self) -> Tuple[pd.DataFrame, np.ndarray]:
        """Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student.

    Returns
    -------
    df : pd.DataFrame
        The corrected DataFrame after insertion of the mean grade
    arr : np.ndarray
            Row indices of the students that their new grades were generated
        """
        grades=self.data[["q1","q2","q3","q4","q5"]]
        grades = grades.apply(pd.to_numeric, errors="coerce")
        missing_grades = grades.loc[:, "q1":"q5"].isna().any(axis=1)
        missing_row_idx = grades[missing_grades].index.to_numpy()
        for idx in missing_row_idx:
            grades.loc[idx]=grades.loc[idx].fillna(grades.loc[idx].mean(skipna=True))
        self.data.loc[:, "q1":"q5"] = grades
        return self.data, missing_row_idx

    def score_subjects(self, maximal_nans_per_sub: int = 1) -> pd.DataFrame:
        """Calculates the average score of a subject and adds a new "score" column
        with it.

        If the subject has more than "maximal_nans_per_sub" NaN in his grades, the
        score should be NA. Otherwise, the score is simply the mean of the other grades.
        The datatype of score is UInt8, and the floating point raw numbers should be
        rounded down.

        Parameters
        ----------
        maximal_nans_per_sub : int, optional
            Number of allowed NaNs per subject before giving a NA score.

        Returns
        -------
        pd.DataFrame
            A new DF with a new column - "score".
        """
        grade_df=self.data.copy()
        grades = grade_df.loc[:,"q1":"q5"].apply(pd.to_numeric, errors="coerce")
        nacheck = grades.isna().sum(axis=1)
        nacheck=nacheck<=maximal_nans_per_sub
        grade_df["score"] = pd.Series(pd.NA, index=grade_df.index, dtype="UInt8")
        means = np.floor(grades.loc[nacheck].mean(axis=1, skipna=True))
        grade_df.loc[nacheck, "score"] = means.astype("UInt8")
        return grade_df

    
    def correlate_gender_age(self) -> pd.DataFrame:
        """Looks for a correlation between the gender of the subject, their age
        and the score for all five questions.

    Returns
    -------
    pd.DataFrame
        A DataFrame with a MultiIndex containing the gender and whether the subject is above
        40 years of age, and the average score in each of the five questions.
    """
        df=self.score_subjects()
        #df=self.data.copy()
        df = df.groupby(['gender', self.data["age"] > 40]
        )[["q1", "q2", "q3", "q4", "q5"]].mean()
        return df
