import pathlib
import pandas as pd
import numpy as np
from typing import Union, Tuple
import matplotlib.pyplot as plt

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """

    def __init__(self, data_fname: Union[pathlib.Path, str]):
        """
        Initialize a new QuestionnaireAnalysis instance.

        Parameters
        ----------
        data_fname : Path/str
            file name (string) or file path

        """
        self.data_fname = pathlib.Path(data_fname)

    def read_data(self):
        """Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        with open(self.data_fname, 'r') as file:
            self.data = pd.read_json(file)
        return self.data
    
    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        """Calculates and plots the age distribution of the participants.

        Returns
        -------
        hist : np.ndarray
            Number of people in a given bin
        bins : np.ndarray
            Bin edges
        """
        bin_edges = np.arange(0, 110, 10)
        ages = self.data['age'].dropna()

        hist, bins = np.histogram(ages, bins=bin_edges)

        # Plot the histogram
        plt.figure()
        plt.hist(ages, bins=bins, edgecolor='black', align='left')
        plt.xticks(bins)
        plt.xlabel("Ages")
        plt.ylabel("# of Participants")
        plt.title("Age Distribution")
        plt.tight_layout()
        plt.show()

        return hist, bins

   